import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import './PublicReportPage.css';

const PublicReportPage = () => {
    const { reportId } = useParams();
    const [report, setReport] = useState(null);
    const [error, setError] = useState('');

    useEffect(() => {
        const fetchReport = async () => {
            try {
                const response = await axios.get(`http://127.0.0.1:8000/reports/public/${reportId}`);
                setReport(response.data);
            } catch (err) {
                setError('Could not find or load the requested report.');
            }
        };
        fetchReport();
    }, [reportId]);

    if (error) {
        return <div className="public-report-container"><div className="report-card"><h1>Error</h1><p>{error}</p></div></div>;
    }

    if (!report) {
        return <div className="public-report-container"><div className="report-card"><h1>Loading Report...</h1></div></div>;
    }
    
    const API_URL = 'http://127.0.0.1:8000';
    const fingerprintUrl = `${API_URL}${report.report_data.fingerprint_chart_url}`;
    const trajectoryUrl = `${API_URL}${report.report_data.trajectory_chart_url}`;

    return (
        <div className="public-report-container">
            <div className="report-card">
                <header className="report-header">
                    <h1>CogniPath AI Learning Report</h1>
                    <h2>For: {report.user_name}</h2>
                </header>

                <p className="report-summary">{report.report_data.dashboard_summary}</p>

                <div className="charts-container">
                    <div className="chart-wrapper">
                        <h3>Cognitive Fingerprint</h3>
                        <img src={fingerprintUrl} alt="Cognitive Fingerprint Chart" />
                    </div>
                    {report.report_data.trajectory_chart_url && (
                        <div className="chart-wrapper">
                            <h3>Learning Trajectory</h3>
                            <img src={trajectoryUrl} alt="Learning Trajectory Chart" />
                        </div>
                    )}
                </div>
                 <footer className="report-footer">
                    <p>Generated by 🧠 CogniPath AI</p>
                </footer>
            </div>
        </div>
    );
};

export default PublicReportPage;

